language: node_js

node_js:
  - '14'
  - '12'
  - '10'

env:
  global:
    - FORCE_COLOR=1

install:
  - npm install

script:
  - npm test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      os: linux
      node_js: '14'
      install: skip
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: oPazLnsp4pyiI9MzuKdpYhKOS6NRBxyCecGB6xUfyTndBdaUZHTwl80dxd1lx3i2JtcDsSPr6oEBFz8XZPV2OojRjpUj5hyckytRfcWNOSQv1Dz6U1ZIjWOzQq92aVwrPvZ0bpNP8DBdPyh3l62jIHazng4idEV8J2D8asdgJtz38XefYAQiCPT2MRudOUhAY2exf4Rj1IN94NlTwMgw6g0YscgELh70nGjdol5b6vtdqkDKdtaFK5ZT6vVZ9PZxVS7IHKHilGhMRHyWTjGnq9jceyeNCdRFbTM0f5E/WIortkXOXquQxQHSxD+kQWghwLsqlzNgpYl//ZmzZeceNybI0+wtVyViFYjI1cGB1Pur9r2+Y1R9JMU1lad3+X+PP+GOB6+VyUQr76xISqAkusWXW1e3jv1ShYI5F+xNdr6nIEcD15LixCH0+FWZcqtFTAdBLltDsiRCjUAevNuA05O/TjrxHKcKB5bFpZPrL5kFGVkKSrD9U2bMPw9Npzn/46xoT0AaeZzD4+haWqS0pf6XrJpi0vfYgdINnEbSrvtj26JhD04lPa6oONWKB0rtvfRFa897F1UTBMnb5TiKFdRrBsQYr9/Rg6OOQjMyIck25UQEOFOH4480bgjE83CvmaImfq5reuForC9b1k1FheMyI8pyqbICzwevv/Iu8EE=
        on:
          tags: true
          repo: catdad/wait-for-throwable
